server.forward-headers-strategy=native
app.openapi.server-url=https://${RAILWAY_PUBLIC_DOMAIN}

emit.security.jwt.secret=${EMIT_SECURITY_JWT_SECRET}
emit.security.jwt.expiration-ms=${EMIT_SECURITY_JWT_EXPIRATION_MS}
emit.admin.username=${EMIT_ADMIN_USERNAME}
emit.admin.password=${EMIT_ADMIN_PASSWORD}
